#!/usr/bin/env bash
set -euo pipefail

# scaffold.sh - interactive setup for a fresh clone of agent-qa-harness-template.
# See docs/CUSTOMIZATION.md for the full adapter spec.

# Working directory must be the repo root. Detect.
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
cd "$REPO_ROOT"

# Refuse to run under a Windows UNC path (//wsl.localhost/...). Windows interop
# reinterprets WSL paths as UNC routes, breaking sed/awk in subtle ways. Open a
# WSL terminal and cd to the native Linux path (e.g. ~/projects/my-app-qa) instead.
if [[ "$REPO_ROOT" == //wsl* || "$REPO_ROOT" == \\\\wsl* ]]; then
  echo "error: scaffolder cannot run from a Windows UNC path. Open a WSL terminal and cd to the linux path."
  exit 1
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

prompt() {
  local question=$1 default=$2 var
  read -r -p "$question [$default]: " var
  echo "${var:-$default}"
}

# sed_escape: escape \, &, and the | delimiter so user-provided values are
# treated as literal strings in a sed replacement (delimiter is |).
sed_escape() {
  printf '%s' "$1" | sed -e 's/[\\&|]/\\&/g'
}

# ---------------------------------------------------------------------------
# Adapter writers
# ---------------------------------------------------------------------------

write_adapter_next_supabase() {
  local path=$1
  cat > "$path" <<'HEREDOC'
// tests/e2e/adapters/next-supabase.ts
// Generated by scaffold.sh. Edit to match the consuming app.
// See docs/CUSTOMIZATION.md for the full StackAdapter interface and pattern notes.

import { chromium } from '@playwright/test';
import type { StackAdapter } from './types';

export const nextSupabase: StackAdapter = {
  async captureAuthState({ url, statePath, role }) {
    const browser = await chromium.launch({ headless: false });
    const ctx = await browser.newContext({
      viewport: { width: 1280, height: 900 },
      // CUSTOMIZATION: set the locale used by your app's i18n config
      locale: 'en-US',
    });
    const page = await ctx.newPage();
    // CUSTOMIZATION: this is the auth entry point for the Supabase OAuth flow
    await page.goto(`${url}/auth/login`);
    console.log(`Sign in as ${role}. Press Enter when at the dashboard.`);
    await new Promise((res) => process.stdin.once('data', res));
    await ctx.storageState({ path: statePath });
    await browser.close();
  },

  async captureDbState({ sessionId, tables }) {
    // CUSTOMIZATION: call the qa_capture_state RPC on the consuming app's Supabase project.
    // The RPC takes a session_id UUID and returns the requested tables as JSON.
    // Route this through the host's authenticated session using SUPABASE_SECRET_KEY
    // so RLS policies are satisfied without granting direct DB access to the harness.
    //
    // Example (fill in with the consuming app's supabase client import):
    //
    //   import { createClient } from '@supabase/supabase-js';
    //   const supabase = createClient(
    //     process.env.NEXT_PUBLIC_SUPABASE_URL!,
    //     process.env.SUPABASE_SECRET_KEY!,
    //   );
    //   const { data, error } = await supabase.rpc('qa_capture_state', {
    //     p_session_id: sessionId,
    //     p_tables: tables,
    //   });
    //   if (error) throw new Error(error.message);
    //   return data as Record<string, unknown[]>;
    throw new Error('Implement against the consuming app supabase client');
  },

  requiredEnvVars: [
    'NEXT_PUBLIC_SUPABASE_URL',
    'SUPABASE_SECRET_KEY',
  ],
};
HEREDOC
}

write_adapter_next_clerk() {
  local path=$1
  cat > "$path" <<'HEREDOC'
// tests/e2e/adapters/next-clerk.ts
// Generated by scaffold.sh. Edit to match the consuming app.
// See docs/CUSTOMIZATION.md for the full StackAdapter interface and pattern notes.

import { chromium } from '@playwright/test';
import type { StackAdapter } from './types';

export const nextClerk: StackAdapter = {
  async captureAuthState({ url, statePath, role }) {
    const browser = await chromium.launch({ headless: false });
    // Clerk Captcha bypass note: if Clerk presents a captcha on the first sign-in
    // from a fresh Chromium profile, use chromium.launchPersistentContext with a
    // stable userDataDir (e.g. .qa-runs/userDataDir/) so the browser profile
    // looks returning rather than new. Set QA_AUTH_PERSIST=1 to enable.
    const ctx = await browser.newContext({ viewport: { width: 1280, height: 900 } });
    const page = await ctx.newPage();
    // CUSTOMIZATION: navigate to a protected route so Clerk redirects to its own sign-in UI.
    // Do not hard-code the Clerk sign-in URL directly: Clerk changes it frequently.
    await page.goto(`${url}/dashboard`);
    console.log(`Sign in as ${role}. Press Enter when at /dashboard.`);
    await new Promise((res) => process.stdin.once('data', res));
    await ctx.storageState({ path: statePath });
    await browser.close();
  },

  async captureDbState({ sessionId, tables }) {
    // Clerk does not provide a database. The consuming app's own DB (Postgres, MongoDB, etc.)
    // is independent of Clerk. Implement this method against that DB layer.
    //
    // If you do not need DB-state capture, return an empty record:
    //   return {};
    void sessionId;
    void tables;
    return {};
  },

  requiredEnvVars: [
    'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY',
    'CLERK_SECRET_KEY',
  ],
};
HEREDOC
}

write_adapter_stub() {
  local path=$1 framework=$2 auth=$3
  cat > "$path" <<HEREDOC
// tests/e2e/adapters/${framework}-${auth}.ts
// TODO: adapter not yet templated for ${framework}-${auth}
// See docs/CUSTOMIZATION.md for the StackAdapter interface and existing examples.
// File an issue or PR with your stack so we can ship a first-class adapter.

import type { StackAdapter } from './types';

const NOT_TEMPLATED = '${framework}-${auth} adapter is not yet templated. See docs/CUSTOMIZATION.md and fill in by hand.';

export const requiredEnvVars: string[] = [];

export const adapter: StackAdapter = {
  async captureAuthState() {
    throw new Error(NOT_TEMPLATED);
  },
  async captureDbState() {
    throw new Error(NOT_TEMPLATED);
  },
  requiredEnvVars,
};
HEREDOC
}

write_adapter_types() {
  local types_path="tests/e2e/adapters/types.ts"
  cat > "$types_path" <<'HEREDOC'
// tests/e2e/adapters/types.ts
// Generated by scaffold.sh. Shared type definitions for all stack adapters.
// See docs/CUSTOMIZATION.md for usage.

export interface StackAdapter {
  captureAuthState(opts: {
    url: string;
    statePath: string;
    role: 'host' | 'admin' | 'user';
  }): Promise<void>;

  captureDbState(opts: {
    sessionId: string;
    tables: string[];
  }): Promise<Record<string, unknown[]>>;

  requiredEnvVars: string[];
}
HEREDOC
}

write_adapter() {
  mkdir -p tests/e2e/adapters
  write_adapter_types
  case "$ADAPTER_NAME" in
    next-supabase)
      write_adapter_next_supabase "$ADAPTER_PATH"
      ;;
    next-clerk)
      write_adapter_next_clerk "$ADAPTER_PATH"
      ;;
    *)
      write_adapter_stub "$ADAPTER_PATH" "$FRAMEWORK" "$AUTH"
      echo ""
      echo "warning: no first-class adapter for ${ADAPTER_NAME}. wrote a stub. fill it in by hand per docs/CUSTOMIZATION.md."
      echo ""
      ;;
  esac
}

# ---------------------------------------------------------------------------
# Gather answers
# ---------------------------------------------------------------------------

echo "agent-qa-harness scaffolder. Six questions, then we generate the adapter."
echo ""

FRAMEWORK=$(prompt "framework? (next/sveltekit/astro/nuxt)" "next")
AUTH=$(prompt "auth provider? (supabase/clerk/auth0)" "supabase")
DB=$(prompt "database? (postgres/d1/mongo)" "postgres")
HOST=$(prompt "host? (vercel/cloudflare)" "vercel")
LOCALE=$(prompt "primary locale (ISO code)" "en-US")
APP_URL=$(prompt "app URL (default for TEST_TARGET_URL)" "http://localhost:3000")
echo ""

ADAPTER_NAME="${FRAMEWORK}-${AUTH}"
ADAPTER_PATH="tests/e2e/adapters/${ADAPTER_NAME}.ts"
mkdir -p tests/e2e/adapters

# ---------------------------------------------------------------------------
# Write adapter (idempotent: ask before overwriting)
# ---------------------------------------------------------------------------

if [[ -f "$ADAPTER_PATH" ]]; then
  OVERWRITE=$(prompt "$ADAPTER_PATH exists. overwrite? (yes/no)" "no")
  if [[ "$OVERWRITE" == "yes" ]]; then
    write_adapter
    echo "adapter written: $ADAPTER_PATH"
  else
    echo "skipping adapter generation"
  fi
else
  write_adapter
  echo "adapter written: $ADAPTER_PATH"
fi

# ---------------------------------------------------------------------------
# Patch playwright.config.ts: replace all en-US locale entries with chosen locale
# (hits the global use.locale line, the chromium-desktop project locale, and the
#  mobile-iphone-13 project locale, which is what we want)
# ---------------------------------------------------------------------------

if [[ "$LOCALE" != "en-US" ]]; then
  SED_SAFE_LOCALE=$(sed_escape "$LOCALE")
  sed -i.bak "s|locale: 'en-US'|locale: '$SED_SAFE_LOCALE'|g" playwright.config.ts
  rm -f playwright.config.ts.bak
  echo "playwright.config.ts: locale set to $LOCALE"
fi

# ---------------------------------------------------------------------------
# Patch tests/e2e/journeys/journeys.spec.ts: replace the J4 routes array
# (the line immediately after the SCAFFOLDER: marker)
# ---------------------------------------------------------------------------

ROUTES_LINE="    const routes = ['/', '/about', '/nonexistent-smoke'];"

awk -v routes="$ROUTES_LINE" '
  /SCAFFOLDER: replace the route list below/ { print; getline; print routes; next }
  { print }
' tests/e2e/journeys/journeys.spec.ts > tests/e2e/journeys/journeys.spec.ts.tmp \
  && mv tests/e2e/journeys/journeys.spec.ts.tmp tests/e2e/journeys/journeys.spec.ts
echo "journeys.spec.ts: J4 routes updated for $FRAMEWORK"

# ---------------------------------------------------------------------------
# Patch .github/workflows/ci.yml: replace the default TEST_TARGET_URL value
# Only replaces the fallback literal 'http://localhost:3000' in the env block.
# ---------------------------------------------------------------------------

if [[ "$APP_URL" != "http://localhost:3000" ]]; then
  SED_SAFE_URL=$(sed_escape "$APP_URL")
  sed -i.bak "s|'http://localhost:3000'|'$SED_SAFE_URL'|g" .github/workflows/ci.yml
  rm -f .github/workflows/ci.yml.bak
  echo "ci.yml: TEST_TARGET_URL default set to $APP_URL"
fi

# ---------------------------------------------------------------------------
# Update generated-adapter note in README.md (idempotent: replace existing block)
# ---------------------------------------------------------------------------

# Strip any existing scaffold-generated block, then append the new one.
sed -i.bak '/<!-- scaffold-generated:start -->/,/<!-- scaffold-generated:end -->/d' README.md
rm -f README.md.bak

cat <<READMEBLOCK >> README.md

<!-- scaffold-generated:start -->
Generated adapter: $ADAPTER_NAME (framework=$FRAMEWORK, auth=$AUTH, db=$DB, host=$HOST, locale=$LOCALE, target=$APP_URL)
<!-- scaffold-generated:end -->
READMEBLOCK
echo "README.md: scaffold-generated block updated"

# ---------------------------------------------------------------------------
# Next-step checklist
# ---------------------------------------------------------------------------

cat <<EOF

scaffolder done. Next steps:

  1. npm install
  2. TEST_TARGET_URL=$APP_URL npm run populate-auth   (one-time, headed browser)
  3. TEST_TARGET_URL=$APP_URL npm run test:e2e -- --grep "J4"
  4. fill in J1-J3 TODOs in tests/e2e/journeys/journeys.spec.ts

stack summary:
  framework: $FRAMEWORK
  auth:      $AUTH
  db:        $DB
  host:      $HOST
  locale:    $LOCALE
  adapter:   $ADAPTER_PATH
EOF
